version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.0.0
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/simdem

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "46:8c:ff:45:d9:ef:24:7a:a6:7a:7f:d7:77:59:cf:c0"
      - kubernetes/install-kubectl
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run SimDem tests
          command: |
            . venv/bin/activate
            python main.py test test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  workflow:
    jobs:
      - build