version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.0.0
jobs:

  azure-test:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          command: az -v
          name: Verify Azure CLI is installed 
      - run: 
          name: List SP Resoures
          command: az resource list

  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/simdem

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python main.py test test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - azure-test
          
